name: Publish

on:
    push:
        branches: ['master', 'main']

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: valitydev/action-frontend/setup-install@v3
              with:
                  node-version: 'lts/*'
                  release: true
            - uses: valitydev/action-frontend/publish@v3
